<?php

namespace Container6VBNB41;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Sylius_Grid_Console_Command_GridDebug_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.sylius.grid.console.command.grid_debug.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.sylius.grid.console.command.grid_debug.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('sylius:debug:grid', [], 'Debug grid configuration', false, #[\Closure(name: 'sylius.grid.console.command.grid_debug', class: 'Sylius\\Bundle\\GridBundle\\Command\\DebugGridCommand')] fn (): \Sylius\Bundle\GridBundle\Command\DebugGridCommand => ($container->services['sylius.grid.console.command.grid_debug'] ?? $container->load('getSylius_Grid_Console_Command_GridDebugService')));
    }
}
