<?php

namespace Container6VBNB41;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Grid_ConfigurationSortingHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.grid.configuration_sorting_handler' shared service.
     *
     * @return \Sylius\Component\Grid\Configuration\GridConfigurationSortingHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/grid-bundle/src/Component/Configuration/GridConfigurationSortingHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/grid-bundle/src/Component/Configuration/GridConfigurationSortingHandler.php';

        return $container->services['sylius.grid.configuration_sorting_handler'] = new \Sylius\Component\Grid\Configuration\GridConfigurationSortingHandler();
    }
}
