<?php

namespace Container6VBNB41;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Grid_Console_Command_GridDebugService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.grid.console.command.grid_debug' shared service.
     *
     * @return \Sylius\Bundle\GridBundle\Command\DebugGridCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/grid-bundle/src/Bundle/Command/DebugGridCommand.php';

        $container->services['sylius.grid.console.command.grid_debug'] = $instance = new \Sylius\Bundle\GridBundle\Command\DebugGridCommand(($container->services['sylius.grid.chain_provider'] ?? $container->load('getSylius_Grid_ChainProviderService')), ($container->privates['.service_locator.GIuJv7e'] ??= new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [], [])), $container->parameters['sylius.grids_definitions']);

        $instance->setName('sylius:debug:grid');
        $instance->setDescription('Debug grid configuration');

        return $instance;
    }
}
