<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6VBNB41\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6VBNB41/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6VBNB41.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6VBNB41\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6VBNB41\App_KernelDevDebugContainer([
    'container.build_hash' => '6VBNB41',
    'container.build_id' => '95479bd1',
    'container.build_time' => 1763452902,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container6VBNB41');
